package com.keecoding.aseancountries

object Constants {

    const val COUNTRY = "country"
    const val JOINED_DATE = "joined_date"
    const val DESCRIPTION = "description"
    const val IMAGE_SRC = "image_src"

    val COUNTRIES = listOf(
        Country("Indonesia", R.drawable.indonesia, "8 Agustus 1967",
            "Indonesia (pengucapan bahasa Indonesia: [in.ˈdo.nɛ.sja]), dikenal secara resmi sebagai Republik Indonesia, adalah negara kepulauan di Asia Tenggara yang dilintasi garis khatulistiwa dan berada di antara daratan benua Asia dan Oseania, sehingga dikenal sebagai negara lintas benua, serta antara Samudra Pasifik dan Samudra Hindia.\n" +
                    "\n" +
                    "Indonesia merupakan negara terluas ke-14 sekaligus negara kepulauan terbesar di dunia dengan luas wilayah sebesar 1.904.569 km², serta negara dengan pulau terbanyak ke-6 di dunia, dengan jumlah 17.504 pulau. Nama alternatif yang dipakai untuk kepulauan Indonesia disebut Nusantara. Selain itu, Indonesia juga menjadi negara berpenduduk terbanyak ke-4 di dunia dengan penduduk mencapai 270.203.917 jiwa pada tahun 2020, serta negara beragama Islam terbanyak di dunia, dengan penganut lebih dari 230 juta jiwa. Indonesia adalah negara multiras, multietnis, dan multikultural di dunia, seperti halnya Amerika Serikat."
        ),
        Country("Malaysia", R.drawable.malaysia, "8 Agustus 1967",
            "Malaysia (Jawi: مليسيا) adalah sebuah negara federal yang terdiri dari tiga belas negeri (negara bagian) dan tiga wilayah federal di Asia Tenggara dengan luas 330.803 km persegi. Ibu kotanya adalah Kuala Lumpur, sedangkan Putrajaya menjadi pusat pemerintahan federal. Jumlah penduduk negara ini mencapai 32.730.000 jiwa pada tahun 2020. Negara ini dipisahkan ke dalam dua kawasan — Semenanjung Malaysia dan Malaysia Timur — oleh Kepulauan Natuna, wilayah Indonesia di Laut Natuna yang terletak di sebelah Selatan dari Laut China Selatan. Malaysia berbatasan dengan Thailand, Indonesia, Singapura, Brunei, dan Filipina. Negara ini terletak di dekat khatulistiwa dan beriklim tropika. Kepala negara Malaysia adalah seorang Raja atau seorang Sultan yang dipilih secara bergiliran setiap 5 tahun sekali dari antara raja negara-negara bagian yang diperintah. Raja Malaysia biasanya memakai gelar Sri Paduka Baginda Yang di-Pertuan Agong dan pemerintahannya dikepalai oleh seorang Perdana Menteri. Model pemerintahan Malaysia mirip dengan sistem parlementer Westminster."
        ),
        Country("Thailand", R.drawable.thailand, "8 Agustus 1967",
            "Thailand, secara resmi Kerajaan Thailand (bahasa Thai: ราชอาณาจักรไทย, Pengucapan Thai: [raːt̚˥˩.t͡ɕʰa˦˥.ʔaː˧.naː˧.t͡ɕak̚˨˩.tʰaj˧]) yang dibaca Rātcha-āṇāchạk Thai, Rāja-ādnyācạkra Thai; atau (Prathēt Thai, Pradēsa Thai), Muang Thai, atau Mueang Thai (dibaca: \"meng-thai\", sama dengan versi Inggrisnya, berarti \"Negeri Thai\"), adalah sebuah negara di Asia Tenggara yang berbatasan dengan Laos dan Kamboja di timur, Malaysia dan Teluk Siam di selatan, dan Myanmar dan Laut Andaman di barat. Kerajaan Thai dahulu dikenal sebagai Siam sampai tanggal 11 Mei 1949. Kata \"Thai\" (ไทย) berarti \"kebebasan\" dalam bahasa Thai, tetapi juga dapat merujuk kepada suku Thai, sehingga menyebabkan nama Siam masih digunakan di kalangan warga negara Thai terutama kaum minoritas Tionghoa dan Amerika.\n" +
                    "\n" +
                    "Orang-orang Thailand bermigrasi dari Yunnan Tiongkok ke daratan Asia Tenggara selama berabad-abad. Referensi paling awal yang diketahui tentang kehadiran mereka di wilayah tersebut berkaitan dengan pengasingan orang Siam di prasasti abad ke-12 di kompleks kuil Khmer Angkor Wat di Kamboja yang menyebut mereka \"palsu\" atau \"perang lama\". Daerah itu pernah dikuasai oleh berbagai pemerintah negara bagian India seperti Mon, Kekaisaran Khmer, dan negara-negara Melayu, bersaing dengan negara-negara seperti Ngoenyang Thailand, Sukhothai, kerajaan Chiang Mai, Lan Na dan Ayutthaya juga saling bertentangan. Orang-orang Eropa tiba pada abad ke-16, dimulai dengan misi diplomatik Portugis ke Ayutthaya pada tahun 1511. Abad-abad berikutnya melihat berbagai kekuatan kolonial Eropa menduduki wilayah-wilayah di IndoTiongkok, di mana Thailand kehilangan sebagian besar wilayahnya oleh Prancis dan Inggris tetapi tetap satu-satunya. Negara-negara Asia Tenggara yang selamat dari pendudukan. Sejak pemerintahan Raja Rama IV pada pertengahan abad ke-19, Thailand telah berkampanye untuk memodernisasi negara sesuai dengan standar Barat. Hal ini menyebabkan transisi dari monarki absolut ke monarki konstitusional pada tahun 1932. Tetapi 60 tahun berikutnya melihat pemerintahan militer dan demokratis berganti, dengan kudeta terbaru pada Mei 2014."
        ),
        Country("Laos", R.drawable.laos, "23 Juli 1997",
            "Laos (bahasa Laos: ລາວ, Lāo [láːw]), secara resmi Republik Demokratis Rakyat Laos (bahasa Laos: ສາທາລະນະລັດ ປະຊາທິປະໄຕ ປະຊາຊົນລາວ, translit. Sathalanalat Paxathipatai Paxaxôn Lao), adalah sebuah negara yang terkurung daratan di Asia Tenggara, yang berbatasan dengan Myanmar dan Republik Rakyat Tiongkok di sebelah barat laut, Vietnam di timur, Kamboja di selatan, dan Thailand di sebelah barat. Dari abad ke-14 hingga abad ke-18, negara ini disebut Lan Xang atau \"Negeri Seribu Gajah\".\n" +
                    "\n" +
                    "Laos adalah sebuah Negara Republik yang dikelilingi oleh daratan dan terletak di bagian utara Semenanjung Indochina. Laos berasal dari kata Lan Xang yang artinya kerajaan gajah. Negara ini adalah satu-satunya Negara di kawasan Asia Tenggara yang tidak memiliki pantai. Laos pernah dijajah oleh Prancis dan memperoleh kemerdekaan pada 22 Oktober 1953 dalam bentuk kerajaan. Sejak 2 Desember 1975 kerajaan Laos berubah menjadi Republik Laos. Laos adalah salah satu negara komunis dengan kepala pemerintahan berupa presiden yang bernama Thongloun Sisoulith dan dibantu oleh perdana menteri yang bernama Phankam Viphavanh. Jika dilihat dari sudut pandang Geografi Politik, letak wilayah negara Laos yang tidak memiliki wilayah laut atau pantai dikenal dengan sebutan kawasan land-lock. Kondisi ini dianggap kurang menguntungkan dari segi pertahanan dan keamanan, khususnya dari serangan atau invasi bangsa lain. Negara Laos mempunyai lembah sungai subur sehingga banyak menghasilkan tanaman pertanian dan perkebunan, terutama padi, kopi, dan tembakau. Memiliki sumber-sumber tambang mineral, seperti timah, tembaga, emas, dan perak. Wilayahnya didominasi perbukitan dan pegunungan yang tertutup hutan lebat, sehingga menghasilkan kayu sebagai salah satu komoditasnya. Potensi sosial budaya terdiri atas berbagai macam suku bangsa dengan berbagai macam budayanya, masyarakatnya sebagian besar masih patuh pada tradisi, memiliki bahasa nasional, yaitu bahasa Lao. Namun dalam kehidupan sehari-hari, selain bahasa nasionalnya masyarakat juga menggunakan bahasa Thai, Inggris, dan Prancis, memiliki banyak bangunan bersejarah, terutama candi."
        ),
        Country("Kamboja", R.drawable.cambodia, "30 April 1999",
            "Kerajaan Kamboja atau Kingdom of Cambodia adalah sebuah negara berbentuk monarki konstitusional di Asia Tenggara. Negara ini merupakan penerus Kekaisaran Khmer yang pernah menguasai seluruh Semenanjung Indochina antara abad ke-11 dan 14.\n" +
                    "\n" +
                    "Kamboja berbatasan dengan Thailand di sebelah barat, Laos di utara, Vietnam di timur, dan Teluk Thailand di selatan. Sungai Mekong dan Danau Tonle Sap melintasi negara ini.\n" +
                    "\n" +
                    "Menjelang kemerdekaannya, Negara Kesatuan Republik Indonesia banyak membantu negara Kamboja ini. Buku - buku taktik perang karangan perwira militer Indonesia banyak digunakan oleh militer Kamboja. Oleh karenanya, para calon perwira di militer Kamboja, wajib belajar dan dapat berbahasa Indonesia."
        ),
        Country("Vietnam", R.drawable.vietnam, "28 Juli 1995",
            "Republik Sosialis Vietnam(bahasa Vietnam: Cộng Hòa Xã Hội Chủ Nghĩa Việt Nam; Chu Nom: 共和社會主義越南) atau lebih dikenal sebagai Vietnam (Việt Nam; 越南) adalah sebuah negara paling timur di semenanjung Indochina. Vietnam berbatasan dengan Tiongkok di sebelah utara, Laos di sebelah barat laut, Kamboja di sebelah barat daya, dan di sebelah timur terbentang Laut Tiongkok Selatan.\n" +
                    "\n" +
                    "Dengan populasi sekitar 84 juta jiwa, Vietnam merupakan negara terpadat ke-13 di dunia. Vietnam termasuk dalam grup ekonomi \"Next Eleven\"; menurut pemerintah, GDP Vietnam tumbuh sebesar 8.17% pada 2006, negara dengan pertumbuhan tercepat kedua di Asia Timur dan pertama di Asia Tenggara. Pada akhir 2007, menteri keuangan menyatakan pertumbuhan GDP Vietnam diperkirakan mencapai rekor tertinggi dalam sepuluh tahun terakhir sebesar 8.44%."
        ),
        Country("Singapura", R.drawable.singapore, "8 Agustus 1967",
            "Singapura (nama resmi: Republik Singapura) adalah sebuah negara pulau di lepas ujung selatan Semenanjung Malaya, 137 kilometer (85 mi) di utara khatulistiwa di Asia Tenggara. Negara ini terpisah dari Malaysia oleh Selat Johor di utara, dan dari Kepulauan Riau, Indonesia oleh Selat Singapura di selatan. Singapura adalah pusat keuangan terdepan ketiga di dunia dan sebuah kota dunia kosmopolitan yang memainkan peran penting dalam perdagangan dan keuangan internasional. Pelabuhan Singapura adalah satu dari lima pelabuhan tersibuk di dunia.\n" +
                    "\n" +
                    "Singapura memiliki sejarah imigrasi yang panjang. Penduduknya yang beragam berjumlah kira-kira 6 juta jiwa, terdiri dari Orang Tionghoa, Melayu, India, Arab, berbagai keturunan Asia, dan Kaukasoid. 42% penduduk Singapura adalah orang asing yang bekerja dan menuntut ilmu di sana. Pekerja asing membentuk 50% dari sektor jasa. Negara ini adalah yang terpadat kedua di dunia setelah Monako. A.T. Kearney menyebut Singapura sebagai negara paling terglobalisasi di dunia dalam Indeks Globalisasi tahun 2006."
        ),
        Country("Filipina", R.drawable.philippines, "8 Agustus 1967",
            "Filipina, dengan nama resmi disebut sebagai Republik Filipina (bahasa Filipino: Republika ng Pilipinas) adalah sebuah negara kepulauan dan negara kesatuan yang bersistem presidensial dengan berbentuk republik konstitusional di Asia Tenggara, sebelah utara Indonesia, dan timur laut Sabah. Filipina merupakan sebuah negara kepulauan yang terletak di Lingkar Pasifik Barat, negara ini terdiri dari 7.641 pulau. Selama ribuan tahun, warga kepulauan Filipina, dan pekerja keras ini telah mengembangkan sistem cocok tanam padi yang sangat maju, yang menyediakan makanan pokok bagi masyarakatnya.\n" +
                    "\n" +
                    "Filipina adalah negara paling maju di Benua Asia setelah Perang Dunia II, namun sejak saat itu telah tertinggal di belakang negara-negara lain akibat pertumbuhan ekonomi yang lemah, penyitaan kekayaan yang dilakukan pemerintah, korupsi yang luas, dan pengaruh-pengaruh neo-kolonial. Meskipun begitu, saat ini Filipina mengalami pertumbuhan ekonomi yang moderat, yang banyak disumbangkan dari pengiriman uang oleh pekerja-pekerja Filipina di luar negeri, dan sektor teknologi informasi yang sedang tumbuh pesat. Filipina sering kali dianggap sebagai satu-satunya negara di Benua Asia di mana pengaruh budaya Barat terasa sangat kuat.\n" +
                    "\n" +
                    "Masalah-masalah besar negara ini termasuk gerakan separatis Bangsamoro di sebelah selatan Filipina yaitu di region Mindanao, pemberontak-pemberontak dari Tentara Rakyat Baru (New People's Army) yang beraliran komunis di wilayah-wilayah pedesaan, kebijakan-kebijakan pemerintah yang sering tidak konsisten, tingkat kejahatan yang makin meningkat, dan kerusakan lingkungan seperti penebangan hutan, dan polusi laut. Filipina juga mengalami masalah banyaknya penduduk di daerah-daerah perkotaan akibat kurangnya lapangan pekerjaan di wilayah pedesaan, dan tingkat kelahiran yang tinggi."
        ),
        Country("Myanmar", R.drawable.myanmar, "23 Juli 1997",
            "Republik Persatuan Myanmar (bahasa Myanmar: ပြည်ထောင်စု သမ္မတ မြန်မာနိုင်ငံတော်, MLCTS: pranyhtau:ngcu. sammata. mranmanuingngamtau) (pengucapan bahasa Burma: [pjìdàʊɴzṵ θàɴməda̰ mjàɴmà nàɪɴŋàɴdɔ̀]) (juga dikenal sebagai Birma, disebut \"Burman\" di dunia Barat) adalah sebuah negara berdaulat di Asia Tenggara. Myanmar berbatasan dengan India dan Bangladesh di sebelah barat, Thailand dan Laos di sebelah timur dan Tiongkok di sebelah utara dan timur laut. Negara seluas 676.578 km² ini telah diperintah oleh pemerintahan militer sejak kudeta tahun 1988. Negara ini adalah negara berkembang dan memiliki populasi lebih dari 51 juta jiwa (sensus 2014). Ibu kota negara ini sebelumnya terletak di Yangon sebelum dipindahkan oleh pemerintahan junta militer ke Naypyidaw pada tanggal 7 November 2005. Myanmar telah bergabung sebagai anggota Perhimpunan Bangsa-Bangsa Asia Tenggara (ASEAN) sejak tahun 1997.\n" +
                    "\n" +
                    "Peradaban awal di Myanmar termasuk penduduk berbahasa Tibeto-Burma di Burma Utara dan Kerajaan Mon di Burma Selatan. Pada abad ke-9, orang Bamar memasuki lembah atas Sungai Irrawaddy, diikuti dengan didirikannya Kerajaan Pagan tahun 1050-an. Sejak saat itu, bahasa Burma, termasuk budaya dan Buddha Theravada perlahan-lahan menjadi dominan di negara ini. Kerajaan Pagan jatuh akibat invasi Mongol. Pada abad ke-16, setelah disatukan oleh Dinasti Taungoo, negara ini sesaat pernah menjadi kekaisaran terbesar dalam sejarah Asia Tenggara. Pada abad ke-19, Dinasti Konbaung menguasai daerah yang didalamnya termasuk wilayah Myanmar modern saat ini dan sesaat menguasai Manipur dan Assam. Inggris menguasai Myanmar setelah 3 Perang Anglo-Burma pada abad ke-19 dan negara ini kemudian menjadi koloni Inggris. Myanmar mendapatkan kemerdekaan tahun 1948, awalnya sebagai negara demokrasi, tetapi setelah kudeta tahun 1962, negara ini dikuasai militer."
        ),
        Country("Brunnei Darussalam", R.drawable.brunei, "7 Januari 1984",
            "Brunei Darussalam atau Brunei adalah negara berdaulat di Asia Tenggara yang terletak di pantai utara pulau Kalimantan. Negara ini memiliki wilayah seluas 5.765 km² yang menempati pulau Kalimantan dengan garis pantai seluruhnya menyentuh Laut Tiongkok Selatan. Wilayahnya dipisahkan ke dalam negara bagian di Sarawak, Malaysia\n" +
                    "\n" +
                    "Saat ini, Brunei Darussalam memiliki Indeks Pembangunan Manusia tertinggi kedua di Asia Tenggara setelah Singapura, sehingga diklasifikasikan sebagai Negara maju. Menurut Dana Moneter Internasional, Brunei memiliki produk domestik bruto per kapita terbesar kelima di dunia dalam keseimbangan kemampuan berbelanja. Sementara itu, Forbes menempatkan Kerajaan Brunei sebagai negara terkaya kelima dari 182 negara karena memiliki ladang minyak bumi dan gas alam yang luas. Selain itu, Brunei juga terkenal dengan kemakmurannya dan ketegasan dalam melaksanakan Agama Islam, baik dalam bidang pemerintahan maupun kehidupan bermasyarakat. Pada tahun 2020, tercatat bahwa Brunei memiliki penduduk sebanyak 460,345 jiwa."
        )
    )

}